"""Add SearchHistoryLog model

Revision ID: 2e20679cd4fc
Revises: 
Create Date: 2025-05-24 06:44:23.270728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e20679cd4fc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_history_logs',
    sa.Column('user_session_id', sa.String(length=36), nullable=False),
    sa.Column('city_name', sa.String(length=255), nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('searched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_history_logs'))
    )
    op.create_index(op.f('ix_search_history_logs_id'), 'search_history_logs', ['id'], unique=False)
    op.create_index(op.f('ix_search_history_logs_user_session_id'), 'search_history_logs', ['user_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_history_logs_user_session_id'), table_name='search_history_logs')
    op.drop_index(op.f('ix_search_history_logs_id'), table_name='search_history_logs')
    op.drop_table('search_history_logs')
    # ### end Alembic commands ###
