"""Add CitySearchStat model

Revision ID: d1a0aab2cd1c
Revises: 2e20679cd4fc
Create Date: 2025-05-24 06:45:46.233477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1a0aab2cd1c'
down_revision: Union[str, None] = '2e20679cd4fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city_search_stats',
    sa.Column('city_name', sa.String(length=255), nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('search_count', sa.Integer(), nullable=False),
    sa.Column('last_searched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_city_search_stats'))
    )
    op.create_index(op.f('ix_city_search_stats_city_name'), 'city_search_stats', ['city_name'], unique=False)
    op.create_index(op.f('ix_city_search_stats_country_code'), 'city_search_stats', ['country_code'], unique=False)
    op.create_index(op.f('ix_city_search_stats_id'), 'city_search_stats', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_city_search_stats_id'), table_name='city_search_stats')
    op.drop_index(op.f('ix_city_search_stats_country_code'), table_name='city_search_stats')
    op.drop_index(op.f('ix_city_search_stats_city_name'), table_name='city_search_stats')
    op.drop_table('city_search_stats')
    # ### end Alembic commands ###
